<h1>Numpy array Objects</h1>
<p>creating a multi-dimensional array object</p>

In [2]:
import numpy as np
array1=[[11,12,13,14],[22,23,24,25],[33,34,35,36]]
array1_new=np.array(array1)
print(array1)

[[11, 12, 13, 14], [22, 23, 24, 25], [33, 34, 35, 36]]


In [3]:
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [4]:
x=[1,2,3,4]
array2=np.array(x)
#array2=np.asarray(x)
print(array2)

[1 2 3 4]


<h2>Shape and ndim</h2>

In [5]:
array1=[[11,12,13,14],[22,23,24,25],[33,34,35,36]]
array1_new=np.array(array1)

In [6]:
print(array1_new.ndim)

2


In [7]:
x=[1,2,3,4]
array2=np.array(x)
print(array2.ndim)

1


In [8]:
print(array1_new.shape)

(3, 4)


In [9]:
print(array2.shape)

(4,)


<h2>np.arrange() and np.resize()</h2>

In [10]:
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [11]:
print(array1_new.shape)

(3, 4)


In [12]:
array2=array1_new.reshape(4,3)
print(array2)

[[11 12 13]
 [14 22 23]
 [24 25 33]
 [34 35 36]]


In [13]:
array2=array1_new.reshape(6,2)
print(array2)

[[11 12]
 [13 14]
 [22 23]
 [24 25]
 [33 34]
 [35 36]]


In [14]:
array2=array1_new.reshape(12,1)
print(array2)

[[11]
 [12]
 [13]
 [14]
 [22]
 [23]
 [24]
 [25]
 [33]
 [34]
 [35]
 [36]]


In [16]:
array2=array1_new.reshape(1,12)
print(array2)

[[11 12 13 14 22 23 24 25 33 34 35 36]]


In [18]:
array=np.arange(-10,10,2)
print(array, array.ndim, array.shape)

[-10  -8  -6  -4  -2   0   2   4   6   8] 1 (10,)


In [19]:
array1=array.reshape(-1,1)
print(array1)

[[-10]
 [ -8]
 [ -6]
 [ -4]
 [ -2]
 [  0]
 [  2]
 [  4]
 [  6]
 [  8]]


In [20]:
array1=array.reshape(1,-1)
print(array1)

[[-10  -8  -6  -4  -2   0   2   4   6   8]]


<h2>Array Creation Routines</h2>

In [21]:
import numpy as np
x=np.empty((3,2),dtype=np.int)
print(x)

[[101986107472075               0]
 [140506335152112 140507603648816]
 [140506335152048 140507603648816]]


<ipython-input-21-2da6457b4926>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.empty((3,2),dtype=np.int)


<p>It creates an uninitialized array of specified shape and dtype. The elements in an array show random values as they are not initialized.</P>

In [22]:
# array of five zeros. Default dtype is float
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [24]:
x=np.zeros((5,3),dtype=np.float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<ipython-input-24-9e1f2760dec8>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.zeros((5,3),dtype=np.float)


In [25]:
x=np.zeros((5,3),dtype=np.int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


<ipython-input-25-e5bdb62a92a2>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.zeros((5,3),dtype=np.int)


In [26]:
x=np.ones((5,3),dtype=np.int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


<ipython-input-26-a161b07db510>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.ones((5,3),dtype=np.int)


<p> This routine are useful for converting Python sequence into ndarray.</P>

In [27]:
x=np.arange(-10,10,2)
print(x)

[-10  -8  -6  -4  -2   0   2   4   6   8]


<p>This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows -</p>
<b> numpy.arange(start,stop,step,dtype)</b>

<h2>Indexing & Slicing</h2>

In [3]:
array=np.random.randint(0,100,(10,5))
print(array)

[[15 14 16 88 49]
 [78 52  4 56 53]
 [21 77 49 63 20]
 [68 39 72 97 40]
 [64 54 13 92  5]
 [62 76 36  4 83]
 [54 75 25 15 74]
 [41  6 66 90  4]
 [31 93 58 83 92]
 [41 87 54 26 64]]


In [4]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))
array3=array1+array2
print('array1', array1)
print('array2', array2)
print('array3', array3)

array1 [[ 7 20 74]
 [ 6 15 18]
 [ 6  5 51]
 [98 88 58]]
array2 [[47 77  5]
 [55 48 32]
 [62 83 27]
 [74 51 43]]
array3 [[ 54  97  79]
 [ 61  63  50]
 [ 68  88  78]
 [172 139 101]]


In [5]:
array1=np.random.randint(0,100,(4,3))
array2=array1/10
print('array1:',array1)
print('array2:',array2)

array1: [[43 85  4]
 [80 83 64]
 [62 61 10]
 [86 58 77]]
array2: [[4.3 8.5 0.4]
 [8.  8.3 6.4]
 [6.2 6.1 1. ]
 [8.6 5.8 7.7]]


In [6]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))
array3=array1*array2
print('array1', array1)
print('array2', array2)
print('array3', array3)

array1 [[50 61 93]
 [38 57 16]
 [72 54 33]
 [55 12 21]]
array2 [[34 68 14]
 [39 97 35]
 [68  6 92]
 [29 91 93]]
array3 [[1700 4148 1302]
 [1482 5529  560]
 [4896  324 3036]
 [1595 1092 1953]]


In [8]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(3,5))
array3=np.matmul(array1,array2)
print('array1', array1)
print('array2', array2)
print('array3', array3)

array1 [[17 59 21]
 [61 18 99]
 [93 51 75]
 [64  9 95]]
array2 [[58 67 71 10 37]
 [98 39  2 69 57]
 [53 90 73 36 60]]
array3 [[ 7881  5330  2858  4997  5252]
 [10549 13699 11594  5416  9223]
 [14367 14970 12180  7149 10848]
 [ 9629 13189 11497  4681  8581]]


In [9]:
array=np.random.randint(0,100,(5,7))
print(array)

[[49 36 93 60 89 34  9]
 [ 4 82 77 44 59 15 61]
 [ 8  3 79 86  9 30  3]
 [42 82 43 19 66 55 66]
 [96  5 40 59  7 42 94]]


In [10]:
print(np.max(array))

96


In [11]:
print(np.argmax(array))

28


In [12]:
print(np.max(array,axis=0))

[96 82 93 86 89 55 94]


In [13]:
print(np.max(array,axis=1))

[93 82 86 82 96]


In [14]:
print(np.argmax(array,axis=1))

[2 1 3 1 0]


In [17]:
print(np.max(array))

96


In [16]:
print(np.argmax(array))

28


In [18]:
print(np.mean(array))

47.02857142857143


In [19]:
print(np.sum(array))

1646


In [20]:
print(array[0][2])

93


In [21]:
print(array[0:3,2:4])

[[93 60]
 [77 44]
 [79 86]]


In [22]:
print(np.mean(array))

47.02857142857143


In [23]:
print(np.min(array))

3


In [24]:
print(np.min(array,axis=0))

[ 4  3 40 19  7 15  3]


In [25]:
print(np.mean(array,axis=0))

[39.8 41.6 66.4 53.6 46.  35.2 46.6]


In [26]:
array=np.random.randint(0,100,(5,10))
print(array)

[[15 97 68 11 69 22 85 15 59 58]
 [78 62 72 55 75 35 79 59 56 57]
 [25 31 25 34 73 53  5 15 27 24]
 [39 39 58 17 41 28 88 44  6 94]
 [45 45  2 43 48 99 59 20 58  9]]


In [28]:
print(array[2,3])

34


In [27]:
print(array[0:2,0:4])

[[15 97 68 11]
 [78 62 72 55]]


In [29]:
print(array[:,0:4])

[[15 97 68 11]
 [78 62 72 55]
 [25 31 25 34]
 [39 39 58 17]
 [45 45  2 43]]


In [30]:
print(array[:,4])

[69 75 73 41 48]


In [31]:
print(array[:2,:])

[[15 97 68 11 69 22 85 15 59 58]
 [78 62 72 55 75 35 79 59 56 57]]


In [32]:
avg=np.mean(array[:2,:])
print(avg)

56.35
