In [3]:
import numpy as np
import tensorflow as tf
import time

In [4]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [6]:
shape=5000

In [7]:
np_array=np.random.uniform(size=[shape,shape])

In [8]:
np_array

array([[0.13238836, 0.31037202, 0.19251712, ..., 0.14493963, 0.14901484,
        0.2066018 ],
       [0.79061602, 0.21279139, 0.88691831, ..., 0.20027789, 0.88477001,
        0.7842747 ],
       [0.64473004, 0.72299103, 0.21537227, ..., 0.18728278, 0.35243263,
        0.1492517 ],
       ...,
       [0.30911103, 0.02483175, 0.3513129 , ..., 0.21649585, 0.40457943,
        0.02596151],
       [0.9073129 , 0.0852934 , 0.2338686 , ..., 0.71955188, 0.68589035,
        0.05276098],
       [0.51978861, 0.22899989, 0.15648521, ..., 0.16736933, 0.5191866 ,
        0.9529664 ]])

In [9]:
start=time.time()
for i in range(10):
    np.matmul(np_array,np_array)
end=time.time()
time_period=end-start
print(f'{time_period} seconds')

16.54359006881714 seconds


In [10]:
tf_array=tf.random.uniform([shape,shape])

In [11]:
tf_array

<tf.Tensor: shape=(5000, 5000), dtype=float32, numpy=
array([[0.40951157, 0.9964837 , 0.55446184, ..., 0.974321  , 0.74929154,
        0.5328853 ],
       [0.21354163, 0.02643228, 0.33674145, ..., 0.19281065, 0.4646833 ,
        0.5189879 ],
       [0.47846568, 0.05778205, 0.6836307 , ..., 0.18740952, 0.00495958,
        0.42247164],
       ...,
       [0.15630472, 0.33473396, 0.8580073 , ..., 0.0845331 , 0.0444293 ,
        0.4034015 ],
       [0.90133417, 0.47272992, 0.98339653, ..., 0.48827612, 0.257581  ,
        0.9843005 ],
       [0.38519096, 0.9683974 , 0.46146595, ..., 0.60826576, 0.05445719,
        0.77779365]], dtype=float32)>

In [12]:
start=time.time()
for i in range(10):
    tf.matmul(tf_array,tf_array)
end=time.time()
time_period=end-start
print(f'{time_period} seconds')

7.43842625617981 seconds
