In [1]:
import numpy as np
import tensorflow as tf
import time

In [2]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [3]:
shape=5000

In [4]:
np_array=np.random.uniform(size=[shape,shape])

In [5]:
np_array

array([[0.07811126, 0.42989288, 0.36042945, ..., 0.1154702 , 0.31879154,
        0.84216078],
       [0.01590999, 0.55120256, 0.47264997, ..., 0.4306159 , 0.247985  ,
        0.26983759],
       [0.27976805, 0.99485705, 0.58584908, ..., 0.84970257, 0.43891598,
        0.1111292 ],
       ...,
       [0.8086152 , 0.26749181, 0.21745817, ..., 0.99664589, 0.25126021,
        0.01075696],
       [0.21969458, 0.99555958, 0.31378646, ..., 0.30188745, 0.12165583,
        0.11593716],
       [0.07345054, 0.86877296, 0.36417776, ..., 0.81838845, 0.07765158,
        0.38509593]])

In [6]:
start=time.time()
for i in range(10):
    np.matmul(np_array,np_array)
end=time.time()
time_period=end-start
print(f'{time_period} seconds')

16.03449821472168 seconds


In [7]:
tf_array=tf.random.uniform([shape,shape])

In [8]:
tf_array

<tf.Tensor: shape=(5000, 5000), dtype=float32, numpy=
array([[0.01234031, 0.52048707, 0.67671216, ..., 0.674876  , 0.73598075,
        0.33932114],
       [0.28181887, 0.80476046, 0.5125594 , ..., 0.26922107, 0.8154069 ,
        0.96250284],
       [0.19381702, 0.48838854, 0.49402452, ..., 0.25760782, 0.33573568,
        0.45246947],
       ...,
       [0.69105005, 0.61851335, 0.11957717, ..., 0.5725992 , 0.6615535 ,
        0.85683775],
       [0.37651396, 0.81311834, 0.5200013 , ..., 0.4079479 , 0.03798974,
        0.4645728 ],
       [0.862597  , 0.00626051, 0.45889807, ..., 0.70343554, 0.9184369 ,
        0.8047838 ]], dtype=float32)>

In [9]:
start=time.time()
for i in range(10):
    tf.matmul(tf_array,tf_array)
end=time.time()
time_period=end-start
print(f'{time_period} seconds')

7.924069404602051 seconds
