In [1]:
# import necessary libraries
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [2]:
# load dataset
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Example_DL/sonar.csv", header=None)
data=data.values

In [17]:
data.shape

(208, 61)

In [4]:
data[:1]

array([[0.02, 0.0371, 0.0428, 0.0207, 0.0954, 0.0986, 0.1539, 0.1601,
        0.3109, 0.2111, 0.1609, 0.1582, 0.2238, 0.0645, 0.066, 0.2273,
        0.31, 0.2999, 0.5078, 0.4797, 0.5783, 0.5071, 0.4328, 0.555,
        0.6711, 0.6415, 0.7104, 0.808, 0.6791, 0.3857, 0.1307, 0.2604,
        0.5121, 0.7547, 0.8537, 0.8507, 0.6692, 0.6097, 0.4943, 0.2744,
        0.051, 0.2834, 0.2825, 0.4256, 0.2641, 0.1386, 0.1051, 0.1343,
        0.0383, 0.0324, 0.0232, 0.0027, 0.0065, 0.0159, 0.0072, 0.0167,
        0.018, 0.0084, 0.009, 0.0032, 'R']], dtype=object)

In [10]:
# divide dataset into x and y
X= data[:,0:60].astype(float)
Y=data[:,60]

In [7]:
X[1]

array([0.0453, 0.0523, 0.0843, 0.0689, 0.1183, 0.2583, 0.2156, 0.3481,
       0.3337, 0.2872, 0.4918, 0.6552, 0.6919, 0.7797, 0.7464, 0.9444,
       1.    , 0.8874, 0.8024, 0.7818, 0.5212, 0.4052, 0.3957, 0.3914,
       0.325 , 0.32  , 0.3271, 0.2767, 0.4423, 0.2028, 0.3788, 0.2947,
       0.1984, 0.2341, 0.1306, 0.4182, 0.3835, 0.1057, 0.184 , 0.197 ,
       0.1674, 0.0583, 0.1401, 0.1628, 0.0621, 0.0203, 0.053 , 0.0742,
       0.0409, 0.0061, 0.0125, 0.0084, 0.0089, 0.0048, 0.0094, 0.0191,
       0.014 , 0.0049, 0.0052, 0.0044])

In [11]:
Y[1]

'R'

In [13]:
# encode labels
encoder=LabelEncoder()
encoder.fit(Y)
Y= encoder.transform(Y)
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# scale features
scaler=MinMaxScaler()
X=scaler.fit_transform(X)
X

array([[0.13643068, 0.15645092, 0.13567674, ..., 0.18535469, 0.24517906,
        0.06004619],
       [0.32300885, 0.22160309, 0.27201051, ..., 0.10526316, 0.14049587,
        0.08775982],
       [0.18215339, 0.24689241, 0.35611038, ..., 0.36842105, 0.25895317,
        0.16628176],
       ...,
       [0.37389381, 0.18474068, 0.05420499, ..., 0.30892449, 0.20936639,
        0.05773672],
       [0.21238938, 0.14873553, 0.15604468, ..., 0.17391304, 0.09641873,
        0.09699769],
       [0.18067847, 0.15302186, 0.03975033, ..., 0.07551487, 0.16528926,
        0.2517321 ]])

In [16]:
# divide dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [20]:
tf.random.set_seed(42)

# create a model with dropout layers
model=tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation='relu', input_shape=(60,)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# compile the model
model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.005),
              metrics=["accuracy"])

# train the model
epoch_number=100
history=model.fit(X_train,y_train, epochs=epoch_number)

Epoch 1/100
6/6 [==============================] - 1s 4ms/step - loss: 0.6864 - accuracy: 0.5663
Epoch 2/100
6/6 [==============================] - 0s 3ms/step - loss: 0.6761 - accuracy: 0.6024
Epoch 3/100
6/6 [==============================] - 0s 3ms/step - loss: 0.6635 - accuracy: 0.6024
Epoch 4/100
6/6 [==============================] - 0s 3ms/step - loss: 0.6554 - accuracy: 0.6265
Epoch 5/100
6/6 [==============================] - 0s 3ms/step - loss: 0.5609 - accuracy: 0.7048
Epoch 6/100
6/6 [==============================] - 0s 4ms/step - loss: 0.5528 - accuracy: 0.6807
Epoch 7/100
6/6 [==============================] - 0s 4ms/step - loss: 0.5617 - accuracy: 0.7169
Epoch 8/100
6/6 [==============================] - 0s 4ms/step - loss: 0.5423 - accuracy: 0.7470
Epoch 9/100
6/6 [==============================] - 0s 3ms/step - loss: 0.5058 - accuracy: 0.7349
Epoch 10/100
6/6 [==============================] - 0s 3ms/step - loss: 0.5355 - accuracy: 0.7108
Epoch 11/100
6/6 [===========

In [21]:
# evaluate the model
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.3295 - accuracy: 0.9524


[0.32949185371398926, 0.9523809552192688]